"""Initial migration

Revision ID: e1ed950842d0
Revises: f68311ebd9d7
Create Date: 2026-08-17 00:19:09.949560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ed950842d0'
down_revision: Union[str, Sequence[str], None] = 'f68311ebd9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('chk_invite_target_exists', 'invitations', 'email IS NOT NULL OR invited_user_id IS NOT NULL')
    op.create_unique_constraint('uq_event_user_settlement', 'settlements', ['event_id', 'from_user_id', 'to_user_id'])
    op.create_check_constraint('chk_no_self_debt', 'settlements', 'from_user_id != to_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_no_self_debt', 'settlements', type_='check')
    op.drop_constraint('uq_event_user_settlement', 'settlements', type_='unique')
    op.drop_constraint('chk_invite_target_exists', 'invitations', type_='check')
    # ### end Alembic commands ###
